### ISSUE TITLE
focal2() with user-defined functions

### ISSUE THREAD

**Issue by fdetsch** [michaeldorman/starsExtra#1]
Thanks for the wonderful work! Would it be possible to enable user-defined functions in `focal2()`, eg. `raster::modal()`?

**Comment by michaeldorman** [comment]
Thanks! 

Right now it's not possible to pass an R function, such as `raster::modal`, to `focal2`, because the possible functions (at present: `"mean"`, `"sum"`, `"min"`, `"max"`) are predefined in the C code. A modal function is a good idea - it has many uses. I've added it in the package to-do list :-)

(there is also a function named `focal2r`, which is R-based, for comparison of execution speed, where any R function can be passed. However it is much slower and impractical on large rasters.)

**Comment by fdetsch** [comment]
Yeah, I realized just after opening this issue that you were sticking to standard functions for a reason 😅
I agree that native R functions are pretty cumbersome when it comes to larger amounts of data. Since modal value calculation is a rather common feature in raster data processing, any thoughts in that direction would be highly appreciated!

**Comment by michaeldorman** [comment]
I added an option `fun="mode"` in `focal2` (https://github.com/michaeldorman/starsExtra/commit/6da190073bd7e721470c737488526c47517b3841). If you use it and encounter any issues will be happy to hear! 

At the moment, in case of ties the first encountered mode is returned. I added in the to-do list that this should be expanded with other options for dealing with ties, like in `raster::modal` (first, last, min, max, random).

**Comment by fdetsch** [comment]
Awesome, thanks! I'll give it a shot at the next opportunity.

**Comment by fdetsch** [comment]
Just wanted to give you a quick feedback that this works like a charm 😎 thanks again!

**Comment by michaeldorman** [comment]
Glad to hear, thanks! :-)
