### ISSUE TITLE
`slope()` returns unrealistic angles

### ISSUE THREAD

**Issue by fdetsch** [michaeldorman/starsExtra#3]
I want to calculate the slope from the attached [DEM](https://github.com/michaeldorman/starsExtra/files/6981759/dem-nad83.zip). Using **raster**, I get:

```r
library(raster)

rst = "dem-nad83.tif" |> 
  raster()

trn = terrain(
  rst
  , unit = "degrees"
)

quantile(
  trn
)
#        0%        25%        50%        75%       100% 
# 0.2190702 13.0571141 16.8310452 21.4173564 31.0428911 
```

Moving to **starsExtra**, `slope()` gives odd results in the sense that the returned angles cannot be real:

```r
library(starsExtra)

strs = "dem-nad83.tif" |> 
  read_stars()

slp = slope(
  strs
)

quantile(
  slp[[1]]
  , na.rm = TRUE
)
#       0%      25%      50%      75%     100% 
# 89.86296 89.99725 89.99796 89.99840 89.99904 
```

Since the DEM comes in `+proj=longlat +datum=NAD83 +no_defs`, I suspected this might have something to do with the CRS. However, projecting to UTM zone 11 and then trying to calculate the slope prints the following error (might be a different issue):

```r
strs = "dem-nad83.tif" |> 
  read_stars() |> 
  st_transform(
    crs = 32611
  )

slp = slope(
  strs
)
```

> Error in slope(strs) : NA/NaN/Inf in foreign function call (arg 6)

As always, any help would be highly appreciated!

**Comment by michaeldorman** [comment]
You rasied several issues which I haven’t considered, and this is very helpful, thanks! 

Basically, `starsExtra::slope` is only appropriate for projected rasters, as the resolution (which is part of the slope calculation) is assumed to be in the same units as the elevation values.

``` r
library(starsExtra)
library(raster)
```

1.  Running `starsExtra::slope` on geographical rasters results in nonsensical values, as you mentioned, because the functions considers the resolution to be in meters while in reality it is in decimal degrees:

``` r
r = read_stars("dem-nad83.tif")
s = slope(r)
s
```

    ## stars object with 2 dimensions and 1 attribute
    ## attribute(s):
    ##               Min.  1st Qu.   Median     Mean 3rd Qu.     Max. NA's
    ## slope [°] 89.86296 89.99725 89.99796 89.99714 89.9984 89.99904 1929
    ## dimension(s):
    ##   from to   offset        delta refsys point values x/y
    ## x    1 75 -118.259  9.25926e-05  NAD83 FALSE   NULL [x]
    ## y    1 55  45.9052 -9.25926e-05  NAD83 FALSE   NULL [y]

2.  Using `st_transform` creates a special type of raster (`curvilinear grid`) which doesn’t have fixed x/y resolutions (each pixel has its own coordinates), therefore the slope calculation cannot be accomplished at all:

``` r
r = read_stars("dem-nad83.tif")
r = st_transform(r, crs = 32611)
s = slope(r)
```

    ## Error in slope(r): NA/NaN/Inf in foreign function call (arg 6)

3.  A possible solution is to reproject the raster using `st_warp`, which does create an ordinary projected raster. However, the resulting `slope` result is distorted due to the effect of resampling which is an inevitable part of the reprojection procedure. This is a very common problem in GIS workflows:

``` r
r = read_stars("dem-nad83.tif")
r = st_warp(r, crs = 32611)
s = slope(r)
plot(as(s, "Raster"))
```

![unnamed-chunk-4-1](https://user-images.githubusercontent.com/9386655/129476461-d769b1f4-26ed-4826-9e3f-e861f12d0708.png)


4.  The closest result compared to `raster::terrain` is obtained when keeping the `stars` object as is, but assigning “new” x/y resolutions, as if it was projected. To do that, we can take the average projected dimensions all pixels, and assume that all pixels share those average dimensions. This is an approximation, which is less accurate as the area in question gets larger.

``` r
r = read_stars("dem-nad83.tif")

# Get average projected resolution
tmp = st_as_sf(r)
tmp = st_transform(tmp, 32611)
tmp = lapply(st_geometry(tmp), st_bbox)
tmp = lapply(tmp, function(x) c(x[3]-x[1], x[4]-x[2]))
x_res = mean(sapply(tmp, "[", 1))
x_res
```

    ## [1] 7.34412

``` r
y_res = mean(sapply(tmp, "[", 2))
y_res
```

    ## [1] 10.40042

``` r
# Assign resolution
r = st_set_dimensions(r, 1, delta = x_res, offset = 0)
r = st_set_dimensions(r, 2, delta = -y_res, offset = 0)

# Calculate slope
s = slope(r)
plot(as(s, "Raster"))
```

![unnamed-chunk-5-1](https://user-images.githubusercontent.com/9386655/129476466-d84f6571-fd66-4cd5-9cb0-3a32de0aa971.png)


I’m not sure if `raster` handles the situation in a similar way or not… 

Meanwhile I’ll add checks to make sure that `starsExtra` does not proceed with calculating `slope` if the raster is either in a geographical CRS or in a curvilinear grid.

**Comment by fdetsch** [comment]
Thanks. Adding a little more transparency will surely improve the user understanding. Meanwhile, this last piece of code is a clever workaround as my areas of interest are generally rather small and the results won't have to be 100% accurate anyway.
